export const analysisData = {
  "generatedAt": "2026-06-09T08:01:59.406Z",
  "dateRange": [
    "2026-06-04",
    "2026-06-05",
    "2026-06-06",
    "2026-06-07",
    "2026-06-08"
  ],
  "method1": {
    "totalAlerts": 265,
    "uniqueSites": 184,
    "byCode": {
      "EM690-0001": 153,
      "USER-0016": 48,
      "AL690-0055": 64
    },
    "byRegion": {
      "Adamawa": 8,
      "North": 8,
      "South": 13,
      "Extreme North": 30,
      "NorthWest": 28,
      "East": 10,
      "Littoral": 25,
      "Centre": 29,
      "SouthWest": 18,
      "West": 15
    },
    "bySeverity": {
      "Warning": 153,
      "Minor": 112
    },
    "sites": [
      {
        "Site": "IHS_NGD_013M",
        "Region": "Adamawa",
        "Address": "T876-Ngaoundere EPC",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_GAR_059M",
        "Region": "North",
        "Address": "T1210SAGAMLA",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Grid ACEM disconnect | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_EBO_014O",
        "Region": "South",
        "Address": "CTR_145-Meyo-Centre",
        "Priority": "P2",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_015O",
        "Region": "Extreme North",
        "Address": "EXN_082-Maroua-Loperey",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_015O",
        "Region": "Adamawa",
        "Address": "ADM_058-Ngd-Trouamala",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_GAR_108O",
        "Region": "North",
        "Address": "NRD_083Garoua-Sabongari-Lainde-IHS",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Grid ACEM disconnect",
        "AlertCount": 3
      },
      {
        "Site": "IHS_GAR_049O",
        "Region": "North",
        "Address": "NRD_028-Ribao",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_044O",
        "Region": "NorthWest",
        "Address": "NRD_034-Balikumbat-Palais",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_BER_035M",
        "Region": "East",
        "Address": "T1220-Djira",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_291M",
        "Region": "Littoral",
        "Address": "T233-Pont Bascule Yassa",
        "Priority": "TIS",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_DLA_302O",
        "Region": "Littoral",
        "Address": "LIT_110-Yabassi",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Gen Only",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Acem Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_YND_408M",
        "Region": "Centre",
        "Address": "T755-Evodoula",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_LMB_134M",
        "Region": "SouthWest",
        "Address": "T2534_Limbe Mile 1",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EDA_025M",
        "Region": "Littoral",
        "Address": "T762-Sikom Mtn",
        "Priority": "TIS",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_212M",
        "Region": "Adamawa",
        "Address": "T2879Batoua Godole",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 GEN ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_011O",
        "Region": "Extreme North",
        "Address": "EXN_068-Maroua-Stade",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_039M",
        "Region": "East",
        "Address": "T909-Djende",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | ACEM1 No Communication | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_LMB_022M",
        "Region": "SouthWest",
        "Address": "T185-Moliwe",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BER_046O",
        "Region": "East",
        "Address": "EST_054-Ndokayo",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_726M",
        "Region": "Centre",
        "Address": "T3349NATCHIGAL",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Grid ACEM disconnect | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_GAR_056M",
        "Region": "North",
        "Address": "T894-GUIDJIBA894",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Hybrid-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EBO_1034M",
        "Region": "Littoral",
        "Address": "T2767NYETE V15",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Grid ACEM disconnect",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BMD_083O",
        "Region": "NorthWest",
        "Address": "NRO_021-Ma",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_060M",
        "Region": "NorthWest",
        "Address": "T348-Bachuo Ntai",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_431M",
        "Region": "Centre",
        "Address": "T494-Nkoteng",
        "Priority": "TIS",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_FBN_102O",
        "Region": "West",
        "Address": "OST_027Lamape",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_087O",
        "Region": "Extreme North",
        "Address": "EXN_048-Gobo",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 ACEM disconnect | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BMD_0049M",
        "Region": "NorthWest",
        "Address": "T1280Ndu Mbakfu",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_KMB_053M",
        "Region": "NorthWest",
        "Address": "T685-Tinto",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_KRI_023M",
        "Region": "Littoral",
        "Address": "T043-Campo",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Acem disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BMD_069O",
        "Region": "NorthWest",
        "Address": "NRO_032-Belo",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_426O",
        "Region": "West",
        "Address": "CTR_226-Mbangassina",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_GAR_115M",
        "Region": "North",
        "Address": "T1408DEMBO",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_LMB_116M",
        "Region": "SouthWest",
        "Address": "T3101-Limbe Stadium",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Grid ACEM disconnect | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_MAR_044M",
        "Region": "Extreme North",
        "Address": "T1403Mokong",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BUA_013M",
        "Region": "SouthWest",
        "Address": "T1778Buea G.R.A.",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Acem Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BUA_041O",
        "Region": "SouthWest",
        "Address": "LIT_178-Missellele",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_BAF_322O",
        "Region": "West",
        "Address": "OST_186Bamenyam",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM disconnect",
        "AlertCount": 3
      },
      {
        "Site": "IHS_MBG_003M",
        "Region": "SouthWest",
        "Address": "T479-Mbanga Town",
        "Priority": "P1",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_SGM_013O",
        "Region": "South",
        "Address": "CTR_111-Zoetele",
        "Priority": "P2",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_YND_382M",
        "Region": "South",
        "Address": "T677-Memiam",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 ACEM Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_SGM_011M",
        "Region": "South",
        "Address": "T678-Mvoutessi",
        "Priority": "TIS",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Hybrid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_DLA_003O",
        "Region": "Littoral",
        "Address": "LIT_381-Pain-Magique",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_537M",
        "Region": "Centre",
        "Address": "T1550_Mefou Assi",
        "Priority": "P2",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 2
      },
      {
        "Site": "IHS_LMB_135M",
        "Region": "SouthWest",
        "Address": "T1670 Limbe Mile 3",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_MAR_031M",
        "Region": "Extreme North",
        "Address": "T1389ZOKOK LADDEO",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Grid ACEM disconnect | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_MBG_002M",
        "Region": "SouthWest",
        "Address": "T1726Mbanga Q8",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_129O",
        "Region": "Centre",
        "Address": "CTR_200-Bastos-BAT",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_MBG_028M",
        "Region": "SouthWest",
        "Address": "T1298Njombe Kompita",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_700O",
        "Region": "Littoral",
        "Address": "LIT_507-Sibongo",
        "Priority": "P4",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_065O",
        "Region": "NorthWest",
        "Address": "NRO_019-Jakiri",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_334O",
        "Region": "Extreme North",
        "Address": "EXN_143 Maroua Djarengol",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 GEN ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BUA_029M",
        "Region": "SouthWest",
        "Address": "T1782Mutengene Maternity",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Acem Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_EDA_101O",
        "Region": "Littoral",
        "Address": "LIT_121NGOG MBOG",
        "Priority": "P4",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Gen ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_809M",
        "Region": "Centre",
        "Address": "T5041_Nkol-Mebanga",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Solar Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_095M",
        "Region": "Adamawa",
        "Address": "T324-Banyo",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 ACEM Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_DLA_034O",
        "Region": "Littoral",
        "Address": "LIT_411Ngodi-Cimetiere",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_234O",
        "Region": "Littoral",
        "Address": "LIT_127-Beedi",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_407M",
        "Region": "Centre",
        "Address": "T053-Monatele",
        "Priority": "P2",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_305M",
        "Region": "Centre",
        "Address": "T1618NYOM",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_FBN_010M",
        "Region": "West",
        "Address": "T1255-DOUMOUFE",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Gen Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_309M",
        "Region": "East",
        "Address": "T2424_Batouri Kambolepi",
        "Priority": "",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "None",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_BMD_202M",
        "Region": "NorthWest",
        "Address": "T1525Bamenda Ntasen",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_052M",
        "Region": "NorthWest",
        "Address": "T1763Bakebe",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_305M",
        "Region": "West",
        "Address": "T482-Nkondjock",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_201M",
        "Region": "Centre",
        "Address": "T460-Cite Verte",
        "Priority": "P3",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_216M",
        "Region": "Extreme North",
        "Address": "T2148-TOULOUM",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BAF_312M",
        "Region": "West",
        "Address": "T1608FONDJOMEKWET",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Acem Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_YND_453O",
        "Region": "Centre",
        "Address": "CTR_311-Song-Bong",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Acem Diconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_MAR_374M",
        "Region": "Extreme North",
        "Address": "T2902 RHUMZU",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 ACEM Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_KMB_019M",
        "Region": "SouthWest",
        "Address": "T1767Small Ekombe",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "None",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | ACEM1 No Communication | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_KSR_019O",
        "Region": "Extreme North",
        "Address": "EXN_041-Blangoua",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_316O",
        "Region": "Extreme North",
        "Address": "EXN_135BOUGOUDOUM",
        "Priority": "",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_674M",
        "Region": "Centre",
        "Address": "T1477Mfou EPC",
        "Priority": "",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_131O",
        "Region": "Littoral",
        "Address": "LIT_414-Deido-Bonateki",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "USER-0016 | EM690-0001 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Power 1 Acem Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BNB_011M",
        "Region": "Littoral",
        "Address": "T1701-FORET BAR MABANDA",
        "Priority": "P2",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_406M",
        "Region": "Littoral",
        "Address": "T1096Bonadiwoto 2",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_040M",
        "Region": "Extreme North",
        "Address": "T364-Bogo",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EDA_055M",
        "Region": "Littoral",
        "Address": "T1654-NDJOKLOUMBE",
        "Priority": "P4",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Gen ACEM disconnect",
        "AlertCount": 3
      },
      {
        "Site": "IHS_YND_146M",
        "Region": "Centre",
        "Address": "T351-Nsimeyong",
        "Priority": "TIS",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BUA_167M",
        "Region": "SouthWest",
        "Address": "T1780Tole Tea",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_127M",
        "Region": "Centre",
        "Address": "T369-Tsinga",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_361M",
        "Region": "South",
        "Address": "T1564Mbalmayo Mbokoulo",
        "Priority": "P3",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | Power 1 Acem Disconnected",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BMD_2229O",
        "Region": "NorthWest",
        "Address": "NRO_081 - Njinikom",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_FBN_112M",
        "Region": "West",
        "Address": "Koutie_T5034",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_081M",
        "Region": "Adamawa",
        "Address": "T329-Febadi",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_447O",
        "Region": "West",
        "Address": "CTR_091-Bamoko",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_074M",
        "Region": "NorthWest",
        "Address": "T430-Kumbo Bangam",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_298M",
        "Region": "East",
        "Address": "T2757-Ndamano",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_359O",
        "Region": "Extreme North",
        "Address": "EXN_126Guere",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_381O",
        "Region": "Extreme North",
        "Address": "EXN_207-Matafal",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EDA_020O",
        "Region": "Littoral",
        "Address": "CTR_059-Ndokok",
        "Priority": "P4",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_091O",
        "Region": "NorthWest",
        "Address": "NRO_236-Mbiame",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_361M",
        "Region": "NorthWest",
        "Address": "T2261_Bamenda Mbomassa",
        "Priority": "",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Electricity 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_118M",
        "Region": "South",
        "Address": "T2784-Djoum-Atok",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_067M",
        "Region": "NorthWest",
        "Address": "T1066-Sop",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_013M",
        "Region": "NorthWest",
        "Address": "T166-Ndamukong street",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 DCEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BNB_001M",
        "Region": "Littoral",
        "Address": "T334-Royal Hotel Dla",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_120M",
        "Region": "South",
        "Address": "T2802_Sanglou",
        "Priority": "P3",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 GEN ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_LMB_028M",
        "Region": "SouthWest",
        "Address": "T0783Mutengene OMBE",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_012M",
        "Region": "SouthWest",
        "Address": "T1810Kumba Makata",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_GAR_317O",
        "Region": "North",
        "Address": "NRD_101 Gra Foulbere Moussa Yaya",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_208M",
        "Region": "NorthWest",
        "Address": "T0734Nwa OCM",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 GEN ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_122M",
        "Region": "SouthWest",
        "Address": "T3455-bonakama 2",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_GAR_076M",
        "Region": "North",
        "Address": "T1820Gor",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Gen ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BUA_168M",
        "Region": "SouthWest",
        "Address": "T1515MILE 4 Q10",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_096O",
        "Region": "NorthWest",
        "Address": "NRO_230-Sabongari-NRO",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_286M",
        "Region": "East",
        "Address": "T1405Bertoua Mokolo",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_015O",
        "Region": "NorthWest",
        "Address": "NRO_227-Bda-Chinde",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Hybrid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_071M",
        "Region": "West",
        "Address": "T228-Alou Repeater",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001 | USER-0016 | AL690-0055",
        "Descriptions": "ACEM1 No Communication | Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_BMD_016M",
        "Region": "NorthWest",
        "Address": "T1167-MBATU",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_433O",
        "Region": "Centre",
        "Address": "CTR_299-Nguila",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_078M",
        "Region": "Adamawa",
        "Address": "T803-Dir",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_521M",
        "Region": "Littoral",
        "Address": "T1843_YATCHIEKA BLOC 55",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_088O",
        "Region": "Adamawa",
        "Address": "ADM_043-Mayo-Tolere-I",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "AL690-0055",
        "Descriptions": "Energy Meter - Communication Lost",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_321M",
        "Region": "Centre",
        "Address": "T105-Soa",
        "Priority": "TIS",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM 1 Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KMB_107M",
        "Region": "Littoral",
        "Address": "T1191Denver 2",
        "Priority": "P4",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_NGD_076M",
        "Region": "Adamawa",
        "Address": "T804-Danfili",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 DCEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_123M",
        "Region": "Extreme North",
        "Address": "T1943-Tide Goulfey",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_008O",
        "Region": "South",
        "Address": "SUD_012-Nkout",
        "Priority": "P3",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_399O",
        "Region": "Centre",
        "Address": "CTR_146-Mekouda",
        "Priority": "P2",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_161O",
        "Region": "Littoral",
        "Address": "LIT_221-Ndogbong-IUT",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 DCEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_516M",
        "Region": "Centre",
        "Address": "T1690ETOUDI Entr?e du palais",
        "Priority": "P1",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_120M",
        "Region": "Extreme North",
        "Address": "T2590_FOTOKOL 3",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KRI_126M",
        "Region": "Littoral",
        "Address": "T2687_KRIBI LOBE SINOSTEEL",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Gen Only",
        "AlertCodes": "USER-0016 | AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter Disconnected | Energy Meter - Communication Lost | ACEM1 No Communication",
        "AlertCount": 3
      },
      {
        "Site": "IHS_KSR_128M",
        "Region": "Extreme North",
        "Address": "T1975_KOUSSERI 3",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_475M",
        "Region": "Centre",
        "Address": "T1062-Ngoum",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_151M",
        "Region": "Littoral",
        "Address": "T626-Bonamouti",
        "Priority": "",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter - Communication Lost | Power 1 ACEM disconnected",
        "AlertCount": 2
      },
      {
        "Site": "IHS_MAR_063O",
        "Region": "Extreme North",
        "Address": "EXN_050-Kay-Kay",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_759M",
        "Region": "Centre",
        "Address": "T3206 Nkolfoulou Tsinga Village",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EBO_002O",
        "Region": "South",
        "Address": "SUD_264Ebolowa-Angale",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_088O",
        "Region": "Extreme North",
        "Address": "EXN_007-Amchide",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_103M",
        "Region": "East",
        "Address": "T2002DENG DENG",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Gen ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_781M",
        "Region": "Centre",
        "Address": "T2502_BIBOMDJIDJIEL",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_207M",
        "Region": "NorthWest",
        "Address": "T1537NDU COUNCIL",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_231M",
        "Region": "Centre",
        "Address": "T292-Nkolso",
        "Priority": "TIS",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_353M",
        "Region": "NorthWest",
        "Address": "T1048_Bamenda GRA 2",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_212O",
        "Region": "Extreme North",
        "Address": "EXN_095Kaele-Guiedame",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_105M",
        "Region": "Extreme North",
        "Address": "T2890-KOFIA",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_413O",
        "Region": "Centre",
        "Address": "CTR_353-Nguinda",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_446M",
        "Region": "West",
        "Address": "T241-Kalong",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_034M",
        "Region": "NorthWest",
        "Address": "T1488Mbengwi Mile 17",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_GAR_109M",
        "Region": "North",
        "Address": "T1388SANGUERE PAUL",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_025M",
        "Region": "South",
        "Address": "T315-Mintom",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Solar-Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_EDA_049O",
        "Region": "West",
        "Address": "SUO_028-Ndom",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_224M",
        "Region": "Extreme North",
        "Address": "T2901BANGANA",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_004O",
        "Region": "Extreme North",
        "Address": "EXN_094Kousseri-Lacka",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_033O",
        "Region": "East",
        "Address": "EST_008-Djangane",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_081O",
        "Region": "Extreme North",
        "Address": "EXN_024-Mogode",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_383O",
        "Region": "Extreme North",
        "Address": "EXN_210-Gabarairou",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BUA_015M",
        "Region": "SouthWest",
        "Address": "T438-Bokwango",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_217M",
        "Region": "Extreme North",
        "Address": "T2900AMCHIDEE TOWN",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_378M",
        "Region": "Centre",
        "Address": "T1573Eseka Town",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_122M",
        "Region": "Extreme North",
        "Address": "T1578-Blangoua 2",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KSR_016O",
        "Region": "Extreme North",
        "Address": "EXN_013-Fotokol",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BFG_172M",
        "Region": "West",
        "Address": "T2751KOUPA NKAGNAM",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_048M",
        "Region": "NorthWest",
        "Address": "T1041-MBEKONG1041",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KRI_121M",
        "Region": "Littoral",
        "Address": "T1991- SOCAPALM V4",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1  ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_704M",
        "Region": "Centre",
        "Address": "T3560-Bastos Bir",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "AL690-0055 | EM690-0001",
        "Descriptions": "Energy Meter - Communication Lost | Power 1 Grid ACEM disconnect",
        "AlertCount": 2
      },
      {
        "Site": "IHS_YND_366M",
        "Region": "Centre",
        "Address": "T579-Mandoumba",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BER_304M",
        "Region": "East",
        "Address": "T1315-Bertoua 2 Catholic church",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KRI_102O",
        "Region": "Littoral",
        "Address": "SUD_053Kribi Mpalla  (Bitolno)",
        "Priority": "P4",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_KRI_014M",
        "Region": "Littoral",
        "Address": "T0141-Nyete V11",
        "Priority": "TIS",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_2226O",
        "Region": "West",
        "Address": "NRO_100-Bambalang",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Grid ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BFG_013M",
        "Region": "West",
        "Address": "T1035-Kekem",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_DLA_510M",
        "Region": "Littoral",
        "Address": "T2626 CITE BERGE BLOC9",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_110M",
        "Region": "South",
        "Address": "T2758-Monekoo",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Hybrid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Gen ACEM disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_037M",
        "Region": "NorthWest",
        "Address": "T164-Bali",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_001O",
        "Region": "South",
        "Address": "SUD_228-Sangmelima-Ville",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BUA_023O",
        "Region": "SouthWest",
        "Address": "SUO_038-Muea",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_395M",
        "Region": "Centre",
        "Address": "T239-Ondondo",
        "Priority": "TIS",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Solar-Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_528M",
        "Region": "Centre",
        "Address": "T1869MEHANDAN",
        "Priority": "P3",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BFG_021M",
        "Region": "West",
        "Address": "T4584_Lelem",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_443M",
        "Region": "East",
        "Address": "T1627- Nanga Eboko TOWN T1621",
        "Priority": "",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001 | USER-0016 | AL690-0055",
        "Descriptions": "Power 1 Grid ACEM disconnect | Energy Meter Disconnected | Energy Meter - Communication Lost",
        "AlertCount": 3
      },
      {
        "Site": "IHS_YND_381M",
        "Region": "Centre",
        "Address": "T139-Boumnyebel",
        "Priority": "TIS",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_051M",
        "Region": "NorthWest",
        "Address": "T614-Pinyin",
        "Priority": "TIS",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_081O",
        "Region": "NorthWest",
        "Address": "NRO_013-Oku",
        "Priority": "P3",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnect",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_205O",
        "Region": "NorthWest",
        "Address": "NRO_024Babessi-T0",
        "Priority": "P5",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_041O",
        "Region": "Extreme North",
        "Address": "EXN_006-Bogo",
        "Priority": "P2",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_215M",
        "Region": "Extreme North",
        "Address": "T2011MOSKOTA",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 Acem Disconnected",
        "AlertCount": 1
      },
      {
        "Site": "IHS_MAR_402M",
        "Region": "Extreme North",
        "Address": "T4709_FADARE",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar Only",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_BMD_2222M",
        "Region": "NorthWest",
        "Address": "T1814Fundong FM",
        "Priority": "P4",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_YND_421M",
        "Region": "Centre",
        "Address": "T566-Bot Makak",
        "Priority": "P4",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "AlertCodes": "EM690-0001",
        "Descriptions": "ACEM1 No Communication",
        "AlertCount": 1
      },
      {
        "Site": "IHS_SGM_111M",
        "Region": "South",
        "Address": "T3466-EMINEMVOM",
        "Priority": "P4",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Hybrid-Gen-Lithium",
        "AlertCodes": "EM690-0001",
        "Descriptions": "Power 1 ACEM Disconnected",
        "AlertCount": 1
      }
    ]
  },
  "method2": {
    "criteria": "No Comm H = 0, Total Power RH ≈ 120h (5 days), Total Power KWh = 0",
    "totalSites": 124,
    "byRegion": {
      "Adamawa": 3,
      "Centre": 22,
      "East": 7,
      "Extreme North": 17,
      "Littoral": 23,
      "North": 3,
      "NorthWest": 16,
      "South": 8,
      "SouthWest": 18,
      "West": 7
    },
    "sites": [
      {
        "Site": "IHS_NGD_041M",
        "Region": "Adamawa",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_NGD_076M",
        "Region": "Adamawa",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 123.64,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_NGD_078M",
        "Region": "Adamawa",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_112O",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_222M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_231M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 119.57,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_305M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_321M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_357M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_366M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_381M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_399O",
        "Region": "Centre",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_413O",
        "Region": "Centre",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_421M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_454O",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_516M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_528M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_530M",
        "Region": "Centre",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 119.92,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_537M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_674M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_704M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_759M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_765M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 119.99,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_781M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_790M",
        "Region": "Centre",
        "ProjectStatus": "SLA_MATEC",
        "PowerTopology": "Grid Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_033O",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 119.96,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_039M",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_082O",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_103M",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_286M",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BER_304M",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_443M",
        "Region": "East",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120.1,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KSR_004O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120.02,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KSR_016O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KSR_120M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_012O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_041O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_044M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_055M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_063O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_081O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_087O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_088O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_212O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_215M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_224M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_374M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_383O",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MAR_403M",
        "Region": "Extreme North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_068M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120.02,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_131O",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_151M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_161O",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_178O",
        "Region": "Littoral",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_217M",
        "Region": "Littoral",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_269M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_291M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_302O",
        "Region": "Littoral",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_406M",
        "Region": "Littoral",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_510M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_521M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_532M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_EDA_039O",
        "Region": "Littoral",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_EDA_055M",
        "Region": "Littoral",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Hybrid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_EDA_064O",
        "Region": "Littoral",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_107M",
        "Region": "Littoral",
        "ProjectStatus": "SLA",
        "PowerTopology": "Grid Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KRI_014M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KRI_023M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KRI_102O",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KRI_121M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Grid-Hybrid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KRI_126M",
        "Region": "Littoral",
        "ProjectStatus": "SLA_LEC",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_700O",
        "Region": "Littoral",
        "ProjectStatus": "SLA GRATO",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_GAR_042O",
        "Region": "North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_GAR_059M",
        "Region": "North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_GAR_109M",
        "Region": "North",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_034M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_037M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_048M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_051M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_081O",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 119.99,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_096O",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 119.82,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_205O",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_207M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_2222M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Hybrid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_2229O",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 119.59,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_327M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 119.97,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_342M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Solar Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BMD_353M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_053M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_060M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_503M",
        "Region": "NorthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_EBO_002O",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_001O",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_008O",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_013O",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_110M",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Hybrid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_111M",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Hybrid-Gen-Lithium",
        "TotalPowerRH": 119.95,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_SGM_118M",
        "Region": "South",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_382M",
        "Region": "South",
        "ProjectStatus": "SLA_DOWEN",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_013M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_015M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_029M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_041O",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_053M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 119.98,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_167M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BUA_186M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_019M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "None",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_026M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 119.99,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_034M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_102O",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen Only",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_KMB_130M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_LMB_013M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_LMB_022M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_LMB_135M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MBG_003M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MBG_004O",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 148.64,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_MBG_028M",
        "Region": "SouthWest",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BAF_312M",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BAF_322O",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_BFG_006O",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_DLA_305M",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_426O",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_446M",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Grid-Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      },
      {
        "Site": "IHS_YND_448M",
        "Region": "West",
        "ProjectStatus": "SLA_IENG",
        "PowerTopology": "Gen-Lithium",
        "TotalPowerRH": 120,
        "TotalPowerKWh": 0,
        "NoCommH": 0
      }
    ]
  }
} as const;